# Generated by Django 4.0.4 on 2022-07-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('vendor_code', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=1, verbose_name='Наявність')),
                ('is_published', models.BooleanField(default=1, verbose_name='Публікація')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Час та дата створення')),
                ('moderated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата оновленя')),
                ('description', models.TextField(max_length=5000)),
                ('brand', models.CharField(max_length=150)),
                ('main_picture', models.ImageField(blank=True, upload_to='')),
                ('pictures', models.ImageField(blank=True, upload_to='')),
                ('options', models.JSONField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('card_views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категорія')),
            ],
        ),
    ]
