# Generated by Django 4.0.4 on 2022-07-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='uploadphoto/%d%m%Y/'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='uploadphoto/%d%m%Y/'),
        ),
    ]
