# Generated by Django 4.0.4 on 2022-07-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productcard_main_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='pictures',
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(blank=True, upload_to='uploadphoto/%d%m%Y/')),
                ('pictures_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productcard')),
            ],
        ),
    ]
