# Generated by Django 4.0.4 on 2022-07-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_productcard_pictures_pictures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name': 'Зображення', 'verbose_name_plural': 'Зображення'},
        ),
        migrations.AlterModelOptions(
            name='productcard',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterField(
            model_name='productcard',
            name='attributes',
            field=models.JSONField(blank=True, null=True, verbose_name='Атрибути'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='brand',
            field=models.CharField(max_length=150, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='card_views',
            field=models.IntegerField(default=0, verbose_name='Кількість переглядів'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='uploadphoto/%d%m%Y/', verbose_name='Головне зображення'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='old_price',
            field=models.IntegerField(default=0, verbose_name='Стара ціна'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='Опції'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='vendor_code',
            field=models.CharField(max_length=200, verbose_name='Код товара'),
        ),
    ]
