version: '3.9'
services:
  redis:
    image: redis:7-alpine
    restart: always

  worker:
    build: .
    volumes:
      - ./pet:/pet
    command: ['celery', 'worker', '-A', 'app.app', '-l', 'info']


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pet:/pet
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pet_project
      - POSTGRES_PASSWORD=pet_project_pass
      - POSTGRES_DB=pet_project_db_3
volumes:
  postgres_data: